In [25]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(f"torch: v{torch.__version__}\npandas: v{pd.__version__}\nnumpy: v{np.__version__}")

torch: v2.2.2
pandas: v2.2.1
numpy: v1.26.4


## Inroduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

![Scalar|Vector|Matrix|Tensor](images/svmt.png)

In [26]:
# Scalar - a single number
scalar = torch.tensor(7)
scalar

tensor(7)

In [27]:
scalar.ndim

0

In [28]:
scalar.item()

7

In [29]:
# Vector - a number with direction (e.g. wind speed with direction) but can also have many other numbers

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [30]:
vector.ndim

1

In [31]:
vector.shape

torch.Size([2])

In [32]:
# MATRIX - a 2-dimensional array of numbers
MATRIX = torch.tensor([
    [7,8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [33]:
MATRIX.ndim

2

In [34]:
MATRIX.shape

torch.Size([2, 2])

In [35]:
# TENSOR - an n-dimensional array of numbers
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [11,12,13],
]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]]])

In [36]:
TENSOR.ndim

3

In [37]:
TENSOR.shape

torch.Size([1, 4, 3])

# Scalar | Vector | Matrix | Tensor
![Scalar|Vector|Matrix|Tensor](images/00-scalar-vector-matrix-tensor.png)

In [38]:
random_tensor = torch.rand(2, 3, 4)
random_tensor.ndim, random_tensor.shape 

(3, torch.Size([2, 3, 4]))

In [39]:
random_tensor[0]

tensor([[8.0081e-01, 2.3430e-01, 7.7578e-01, 5.7421e-01],
        [3.4589e-04, 1.3654e-01, 1.3167e-01, 9.1286e-01],
        [2.3296e-01, 1.7997e-01, 6.9986e-01, 3.5428e-01]])

In [40]:
range_of_number = torch.arange(0, 10)
range_of_number, range_of_number[1]

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor(1))

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float32,
    device='cpu',
    requires_grad=False)

(
    float_32_tensor,
    float_32_tensor.dtype,
    float_32_tensor.device,
    float_32_tensor.requires_grad,
    float_32_tensor.shape,
    float_32_tensor.size(),
)

(tensor([3., 6., 9.]),
 torch.float32,
 device(type='cpu'),
 False,
 torch.Size([3]),
 torch.Size([3]))

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)

(
    float_16_tensor,
    float_16_tensor.dtype,
    float_16_tensor.device,
    float_16_tensor.requires_grad,
    float_16_tensor.shape,
    float_16_tensor.size(),
)

(tensor([3., 6., 9.], dtype=torch.float16),
 torch.float16,
 device(type='cpu'),
 False,
 torch.Size([3]),
 torch.Size([3]))

In [43]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Manipulation Tensors (tensor operation)

* Addition
* Subtraction
* Division
* Multiplacation (element-wise)
* Matrix Multiplication

#### The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)


![Matrix Multiplacation](images/matrix-multiplication.png)

In [47]:
matrix_a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])

matrix_b = torch.tensor([
    [10, 11],
    [20, 21],
    [30, 31],
])

matrix_ab = torch.matmul(matrix_a, matrix_b)
matrix_ab

tensor([[140, 146],
        [320, 335]])

In [49]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])
