In [73]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(f"torch: v{torch.__version__}\npandas: v{pd.__version__}\nnumpy: v{np.__version__}")

torch: v2.2.2
pandas: v2.2.1
numpy: v1.26.4


## Inroduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

![Scalar|Vector|Matrix|Tensor](images/svmt.png)

In [74]:
# Scalar - a single number
scalar = torch.tensor(7)
scalar

tensor(7)

In [75]:
scalar.ndim

0

In [76]:
scalar.item()

7

In [77]:
# Vector - a number with direction (e.g. wind speed with direction) but can also have many other numbers

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [78]:
vector.ndim

1

In [79]:
vector.shape

torch.Size([2])

In [80]:
# MATRIX - a 2-dimensional array of numbers
MATRIX = torch.tensor([
    [7,8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [81]:
MATRIX.ndim

2

In [82]:
MATRIX.shape

torch.Size([2, 2])

In [83]:
# TENSOR - an n-dimensional array of numbers
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [11,12,13],
]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]]])

In [84]:
TENSOR.ndim

3

In [85]:
TENSOR.shape

torch.Size([1, 4, 3])

# Scalar | Vector | Matrix | Tensor
![Scalar|Vector|Matrix|Tensor](images/00-scalar-vector-matrix-tensor.png)

In [86]:
random_tensor = torch.rand(2, 3, 4)
random_tensor.ndim, random_tensor.shape 

(3, torch.Size([2, 3, 4]))

In [87]:
random_tensor[0]

tensor([[0.3531, 0.7719, 0.8001, 0.4619],
        [0.7602, 0.7689, 0.8622, 0.0168],
        [0.8253, 0.7856, 0.9128, 0.1724]])

In [88]:
range_of_number = torch.arange(0, 10)
range_of_number, range_of_number[1]

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor(1))

In [89]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float32,
    device='cpu',
    requires_grad=False)

(
    float_32_tensor,
    float_32_tensor.dtype,
    float_32_tensor.device,
    float_32_tensor.requires_grad,
    float_32_tensor.shape,
    float_32_tensor.size(),
)

(tensor([3., 6., 9.]),
 torch.float32,
 device(type='cpu'),
 False,
 torch.Size([3]),
 torch.Size([3]))

In [90]:
float_16_tensor = float_32_tensor.type(torch.float16)

(
    float_16_tensor,
    float_16_tensor.dtype,
    float_16_tensor.device,
    float_16_tensor.requires_grad,
    float_16_tensor.shape,
    float_16_tensor.size(),
)

(tensor([3., 6., 9.], dtype=torch.float16),
 torch.float16,
 device(type='cpu'),
 False,
 torch.Size([3]),
 torch.Size([3]))

In [91]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Manipulation Tensors (tensor operation)

* Addition
* Subtraction
* Division
* Multiplacation (element-wise)
* Matrix Multiplication

#### The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)


![Matrix Multiplacation](images/matrix-multiplication.png)

In [92]:
matrix_a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
])

matrix_b = torch.tensor([
    [10, 11],
    [20, 21],
    [30, 31],
])

matrix_ab = torch.matmul(matrix_a, matrix_b)
matrix_ab

tensor([[140, 146],
        [320, 335]])

In [93]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method                        | One-line description                                                                                        |
|-------------------------------|-------------------------------------------------------------------------------------------------------------|
| `torch.reshape(input, shape)` | Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().                               |
| `Tensor.view(shape)`          | Returns a view of the original tensor in a different shape but shares the same data as the original tensor. |
| `torch.stack(tensors, dim=0)` | Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.              |
| `torch.squeeze(input)`        | Squeezes input to remove all the dimenions with value 1.                                                    |
| `torch.unsqueeze(input, dim)` | Returns input with a dimension value of 1 added at dim.                                                     |
| `torch.permute(input, dims)`  | Returns a view of the original input with its dimensions permuted (rearranged) to dims.                     |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.

In [94]:
# Torch Reshape - https://pytorch.org/docs/stable/generated/torch.reshape.html
x = torch.arange(120.)
x, x.shape

(tensor([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
          12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
          24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
          36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
          48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,
          60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
          72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,
          84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
          96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107.,
         108., 109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]),
 torch.Size([120]))

In [95]:
# Torch Reshape - https://pytorch.org/docs/stable/generated/torch.reshape.html
x_reshaped = torch.reshape(x, (2, 3, 4, 5))
x_reshaped, x_reshaped.shape

(tensor([[[[  0.,   1.,   2.,   3.,   4.],
           [  5.,   6.,   7.,   8.,   9.],
           [ 10.,  11.,  12.,  13.,  14.],
           [ 15.,  16.,  17.,  18.,  19.]],
 
          [[ 20.,  21.,  22.,  23.,  24.],
           [ 25.,  26.,  27.,  28.,  29.],
           [ 30.,  31.,  32.,  33.,  34.],
           [ 35.,  36.,  37.,  38.,  39.]],
 
          [[ 40.,  41.,  42.,  43.,  44.],
           [ 45.,  46.,  47.,  48.,  49.],
           [ 50.,  51.,  52.,  53.,  54.],
           [ 55.,  56.,  57.,  58.,  59.]]],
 
 
         [[[ 60.,  61.,  62.,  63.,  64.],
           [ 65.,  66.,  67.,  68.,  69.],
           [ 70.,  71.,  72.,  73.,  74.],
           [ 75.,  76.,  77.,  78.,  79.]],
 
          [[ 80.,  81.,  82.,  83.,  84.],
           [ 85.,  86.,  87.,  88.,  89.],
           [ 90.,  91.,  92.,  93.,  94.],
           [ 95.,  96.,  97.,  98.,  99.]],
 
          [[100., 101., 102., 103., 104.],
           [105., 106., 107., 108., 109.],
           [110., 111., 112., 113., 

In [96]:
# https://pytorch.org/docs/stable/generated/torch.Tensor.view.html
x_view = x_reshaped.view(8, 15)
x_view, x_view.shape

(tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
           12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
           27.,  28.,  29.],
         [ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,
           42.,  43.,  44.],
         [ 45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
           57.,  58.,  59.],
         [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
           72.,  73.,  74.],
         [ 75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,
           87.,  88.,  89.],
         [ 90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101.,
          102., 103., 104.],
         [105., 106., 107., 108., 109., 110., 111., 112., 113., 114., 115., 116.,
          117., 118., 119.]]),
 torch.Size([8, 15]))

In [97]:
# View of a tensor shares the same memory as the original tensor
x_view[7][14] = 420
x_view, x_reshaped

(tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
           12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,
           27.,  28.,  29.],
         [ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,
           42.,  43.,  44.],
         [ 45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
           57.,  58.,  59.],
         [ 60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,
           72.,  73.,  74.],
         [ 75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,
           87.,  88.,  89.],
         [ 90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101.,
          102., 103., 104.],
         [105., 106., 107., 108., 109., 110., 111., 112., 113., 114., 115., 116.,
          117., 118., 420.]]),
 tensor([[[[  0.,   1.,   2.,   3.,   4.],
           [  5.,   6.,   7.,   8.,   9.],
           [ 10.,  11., 

In [98]:
# Torch Stack - Concatenates a sequence of tensors along a new dimension
s = torch.randn(3, 4)
s, s.shape

(tensor([[ 1.8054,  1.0400, -1.1512, -0.6707],
         [-0.8812,  0.4081,  1.1452, -0.9442],
         [-0.9542, -0.7608, -1.2365, -0.3737]]),
 torch.Size([3, 4]))

In [99]:
s1 = torch.stack((s,), dim=2)
s1, s1.shape

(tensor([[[ 1.8054],
          [ 1.0400],
          [-1.1512],
          [-0.6707]],
 
         [[-0.8812],
          [ 0.4081],
          [ 1.1452],
          [-0.9442]],
 
         [[-0.9542],
          [-0.7608],
          [-1.2365],
          [-0.3737]]]),
 torch.Size([3, 4, 1]))

In [100]:
# torch.squeeze - removes all single dimensions from a target tensor
s2 = s1.squeeze()
s2, s2.shape

(tensor([[ 1.8054,  1.0400, -1.1512, -0.6707],
         [-0.8812,  0.4081,  1.1452, -0.9442],
         [-0.9542, -0.7608, -1.2365, -0.3737]]),
 torch.Size([3, 4]))

In [101]:
# Valid dim is 0 <= dim < row
s3 = torch.randn(2, 3, 4)
s3 = s3.unsqueeze(dim=3)
s3, s3.shape

(tensor([[[[ 0.3390],
           [-0.2606],
           [-1.3213],
           [ 0.6503]],
 
          [[-0.2732],
           [-0.4238],
           [ 1.3575],
           [-1.0860]],
 
          [[-0.5972],
           [ 0.1251],
           [ 1.6512],
           [ 0.4602]]],
 
 
         [[[ 0.3078],
           [-0.2249],
           [ 0.1237],
           [-0.5064]],
 
          [[ 0.6669],
           [-0.4931],
           [ 0.5357],
           [-0.3753]],
 
          [[ 0.6239],
           [ 0.3061],
           [ 0.2815],
           [ 0.6674]]]]),
 torch.Size([2, 3, 4, 1]))

In [104]:
# torch.permute - rearrange the diamendions of a target tensor in a specified order
# permute is another form of view
x_original = torch.rand(size=(224, 224, 3)) # height px, width px, color - RGB

# Permute the original tensor to rearrange the axis (or dim) order
# i.e shift 2nd index at first
x_permuited = x_original.permute(2, 0, 1) # color - RGB, height px, width px
print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuited.shape}")

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])
