In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(f"torch: v{torch.__version__}\npandas: v{pd.__version__}\nnumpy: v{np.__version__}")

torch: v2.2.2
pandas: v2.2.1
numpy: v1.26.4


## Inroduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

![Scalar|Vector|Matrix|Tensor](images/svmt.png)

In [9]:
# Scalar - a single number
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
scalar.item()

7

In [25]:
# Vector - a number with direction (e.g. wind speed with direction) but can also have many other numbers

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [26]:
# MATRIX - a 2-dimensional array of numbers
MATRIX = torch.tensor([
    [7,8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [27]:
# TENSOR - an n-dimensional array of numbers
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [11,12,13],
]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 4, 3])

# Scalar | Vector | Matrix | Tensor
![Scalar|Vector|Matrix|Tensor](images/00-scalar-vector-matrix-tensor.png)

In [29]:
random_tensor = torch.rand(2, 3, 4)
random_tensor.ndim, random_tensor.shape 

(3, torch.Size([2, 3, 4]))

In [30]:
random_tensor[0]

tensor([[0.2996, 0.2918, 0.8317, 0.6643],
        [0.0108, 0.8692, 0.3794, 0.5775],
        [0.1576, 0.7241, 0.3031, 0.1192]])